import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import { cn } from '@/lib/utils';
import prisma from '@/lib/prisma';
import { getAuthSession } from '@/lib/auth';
import Providers from '@/components/Providers';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();
  const employments = await prisma.employee.findMany({
    where: {
      user_id: session?.user?.id,
    },
  });
  return (
    <html lang="en">
      <body
        className={cn(
          'flex min-h-screen flex-col min-w-fit dark bg-background',
          inter.className,
        )}
      >
        <Providers>
          <Header userEmployments={employments} />
          <main
            className={cn(
              'flex-grow text-center container max-w-7xl mx-auto text-foreground',
            )}
          >
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
