name: Closed PR into Dev/Main (Merged / Unmerged)

on:
  workflow_dispatch:
  pull_request:
    branches: [dev, main, merge]
    types: [closed]

env:
  NODE_VERSION: 18.13.0

jobs:
  setup-pr-closed-dev:
    # if: github.base_ref == 'dev'
    if: github.base_ref == 'merge'
    runs-on: ubuntu-latest
    environment: Preview
    env:
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PSCALE_SERVICE_TOKEN }}
      PSCALE_ORG_NAME: ${{ vars.PSCALE_ORG_NAME }}
      PSCALE_DB_NAME: ${{ vars.PSCALE_DB_NAME }}
      PSCALE_PWORD_ROLE: ${{ vars.PSCALE_PWORD_ROLE }}
    outputs:
      DB_CHANGES: ${{ steps.db_changes.outputs.DB_CHANGES }}
      PSCALE_BRANCH_NAME: ${{ steps.branch_name.outputs.PSCALE_BRANCH_NAME }}
      EXISTING_PWORD_NAME: ${{ steps.existing_pword.outputs.EXISTING_PWORD_NAME }}
      EXISTING_PWORD_ID: ${{ steps.existing_pword.outputs.EXISTING_PWORD_ID }}
    steps:
      - name: Check github context values
        run: |
          echo "github.base_ref ${{ github.base_ref }}"
          echo "github.event.pull_request.head.ref ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.base.ref ${{ github.event.pull_request.base.ref }}"
          echo "github.head_ref ${{ github.head_ref }}"
          echo "github.base_ref ${{ github.base_ref }}"
          echo "github.event.pull_request.base.ref ${{ github.event.pull_request.merge_commit_sha }} "
          echo "GITHUB_CONTEXT:: $GITHUB_CONTEXT:"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        # cat $GITHUB_EVENT_PATH
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make shell scripts executable
        run: chmod -R +x ./my-scripts/
      - name: Check DB changes on PR (Head vs. Base)
        id: db_changes
        working-directory: ./my-scripts/pscale/
        run: |
          MERGE_COMMIT=${{ github.event.pull_request.merge_commit_sha }}
          COMMIT_ON_BASE=${{ github.event.pull_request.base.sha }}

          source ./check-db-changes.sh $MERGE_COMMIT $COMMIT_ON_BASE

          echo "DB_CHANGES: ${DB_CHANGES}"
          echo "ERROR: $ERROR"
          echo "DB_CHANGES=${DB_CHANGES}" >> "${GITHUB_OUTPUT}"
          echo "ERROR=${ERROR}" >> "${GITHUB_OUTPUT}"

      # COMMIT_ON_HEAD=${{ github.event.pull_request.head.sha }}

      - name: Planetscale Setup
        if: steps.db_changes.outputs.DB_CHANGES == 'true'
        id: pscale_setup
        uses: planetscale/setup-pscale-action@v1
      - name: Get Pscale Branch Name
        if: steps.pscale_setup.outcome == 'success'
        id: branch_name
        working-directory: ./my-scripts/pscale/
        shell: bash
        run: |
          GITHUB_BRANCH_NAME=${{ github.head_ref }}
          GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}

          ./get-pscale-branch-name.sh $GITHUB_BRANCH_NAME $GITHUB_PR_NUMBER

          echo "outputs: PSCALE_BRANCH_NAME / SHORTENED_GH_BRANCH_NAME"
      - name: Get Branch Password if exists
        if: steps.branch_name.outcome == 'success'
        id: existing_pword
        shell: bash
        working-directory: ./my-scripts/pscale/
        run: |
          PSCALE_BRANCH_NAME=${{ steps.branch_name.outputs.PSCALE_BRANCH_NAME }}
          PSCALE_PWORD_NAME=${PSCALE_BRANCH_NAME}-${PSCALE_PWORD_ROLE}

          source ./get-pword-info.sh ${{ env.PSCALE_DB_NAME }} ${PSCALE_BRANCH_NAME} ${{ env.PSCALE_ORG_NAME }} ${PSCALE_PWORD_NAME}

          echo "Step Outputs:"
          echo "EXISTING_PWORD_ID: ${PWORD_ID}"
          echo "EXISTING_PWORD_NAME: ${PWORD_NAME}"

          echo "EXISTING_PWORD_ID=${PWORD_ID}" >> $GITHUB_OUTPUT
          echo "EXISTING_PWORD_NAME=${PWORD_NAME}" >> $GITHUB_OUTPUT

  # no need to check pull_request activity type if closed
  # if: github.base_ref == 'dev' && github.event.pull_request.state == 'closed' && github.event.pull_request.merged == false
  # if: github.base_ref == 'dev' && needs.setup-pr-closed-dev.outputs.DB_CHANGES == 'true'
  pscale-cleanup-pr-dev:
    if: github.base_ref == 'merge' && needs.setup-pr-closed-dev.outputs.DB_CHANGES == 'true'
    needs: setup-pr-closed-dev
    runs-on: ubuntu-latest
    environment: Preview
    env:
      PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PSCALE_SERVICE_TOKEN_ID }}
      PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PSCALE_SERVICE_TOKEN }}
      PSCALE_ORG_NAME: ${{ vars.PSCALE_ORG_NAME }}
      PSCALE_DB_NAME: ${{ vars.PSCALE_DB_NAME }}
      PSCALE_BRANCH_NAME: ${{ needs.setup-pr-closed-dev.outputs.PSCALE_BRANCH_NAME }}
      EXISTING_PWORD_NAME: ${{ needs.setup-pr-closed-dev.outputs.EXISTING_PWORD_NAME }}
      EXISTING_PWORD_ID: ${{ needs.setup-pr-closed-dev.outputs.EXISTING_PWORD_ID }}
      # DB_CHANGES: ${{ needs.setup-pr-closed-dev.outputs.DB_CHANGES }}
    steps:
      - name: Check github context
        run: |
          echo "github.base_ref ${{ github.base_ref }}"
          echo "needs.setup-pr-closed-dev.outputs.DB_CHANGES ${{ needs.setup-pr-closed-dev.outputs.DB_CHANGES }}"
          echo "github.event.pull_request.merged ${{ github.event.pull_request.merged }}"
          echo "github.repository: ${{ github.repository }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Planetscale Setup
        id: pscale_setup
        uses: planetscale/setup-pscale-action@v1
      - name: Get Pscale DR info for Branch, if exists
        id: existing_dr
        working-directory: ./my-scripts/pscale/
        run: |
          ./check-dr-exists.sh "${PSCALE_DB_NAME}" "${PSCALE_BRANCH_NAME}" "${PSCALE_ORG_NAME}"

          echo "step outputs: DR_EXISTS | DR_NUMBER | DR_BRANCH | DR_INTO_BRANCH | DR_APPROVED | DR_STATE | DR_DEPLOY_STATE | DR_DEPLOYABLE"

      # no need to close DR since will be closed after deleting branch
      # - name: Close Pscale Deploy Request
      #   if: steps.existing_dr.outcome == 'success' && github.event.pull_request.merged == false
      #   run: |
      #     PSCALE_DB_NAME=${{ env.PSCALE_DB_NAME }}
      #     DR_NUMBER=${{ steps.existing_dr.outputs.DR_NUMBER }}
      #     PSCALE_ORG_NAME=${{ env.PSCALE_ORG_NAME }}
      #     pscale deploy-request close $PSCALE_DB_NAME $DR_NUMBER --org $PSCALE_ORG_NAME
      # github.event.pull_request.merged needs to be a boolean value, unless enclosed in ${{ }} w/c converts it into a string
      - name: Deploy Pscale Deploy Request
        if: steps.existing_dr.outcome == 'success' && github.event.pull_request.merged == true
        id: deploy_dr
        run: pscale deploy-request deploy ${{ env.PSCALE_DB_NAME }} ${{ env.PSCALE_BRANCH_NAME }} --org ${{ env.PSCALE_ORG_NAME }}
        # run: pscale deploy-request deploy ${{ env.PSCALE_DB_NAME }} ${{ steps.existing_dr.outputs.DR_NUMBER }} --org ${{ env.PSCALE_ORG_NAME }}
      - name: Skip Revert Pscale Deploy Request
        if: steps.deploy_dr.outcome == 'success' && github.base_ref == 'merge'
        run: pscale deploy-request skip-revert ${{ env.PSCALE_DB_NAME }} ${{ steps.existing_dr.outputs.DR_NUMBER }} --org ${{ env.PSCALE_ORG_NAME }}
      - name: Install NodeJS
        if: steps.deploy_dr.outcome == 'success'
        id: install_nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Check Cache for dependencies needed for Prisma DB push and Seed/Reset
        if: steps.install_nodejs.outcome == 'success'
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: deps-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies to enable Prisma DB Push and Seed/Reset
        if: steps.cache_deps.outcome == 'success' && steps.cache_deps.outputs.cache-hit != 'true'
        id: install_deps
        run: npm ci
      # ENABLE THIS AFTER TESTING!!!!!!!!!!!!!!!!!!!!!!!!
      - name: Prisma DB Push & DB Seed/Reset
        # if: false
        run: DATABASE_URL=${{ secrets.PSCALE_SRC_BRANCH_DATABASE_URL }} npm run db:reset

      # need to check DR if State=closed??? we can already delete it right away
      # only delete pscale branch if STATE=closed and DEPLOY_STATE=complete ??? or just delete w/o checking
      # need to check since for gh main branch, we do manual deploy-request apply, skip-revert, and "branch delete" and so that this workflow is more flexible and reusable
      - name: Close Pscale Deploy Request
        if: steps.existing_dr.outcome == 'success' && github.event.pull_request.merged == false
        run: pscale deploy-request close ${{ env.PSCALE_DB_NAME }} ${{ steps.existing_dr.outputs.DR_NUMBER }} --org ${{ env.PSCALE_ORG_NAME }}

      # should always run
      - name: Check existing Pscale DR STATE and DEPLOY_STATE
        id: dr_state
        working-directory: ./my-scripts/pscale/
        run: |
          ./check-dr-exists.sh "${PSCALE_DB_NAME}" "${PSCALE_BRANCH_NAME}" "${PSCALE_ORG_NAME}"

          echo "step outputs: DR_EXISTS | DR_NUMBER | DR_BRANCH | DR_INTO_BRANCH | DR_APPROVED | DR_STATE | DR_DEPLOY_STATE | DR_DEPLOYABLE"
      # should always run when pull_request is closed (whether merged or not) and DR_STATE is closed (whether DEPLOY_State=complete or not)
      - name: Delete Pscale Branch
        if: steps.dr_state.outputs.DR_STATE == 'closed'
        run: pscale branch delete ${{ env.PSCALE_DB_NAME }} ${{ env.PSCALE_BRANCH_NAME }} --org ${{ env.PSCALE_ORG_NAME }} --force
      - name: Delete Caches created by the Opened PR Workflow
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=${{ env.EXISTING_PWORD_NAME }}-${{ env.EXISTING_PWORD_ID }}"

          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=node-cache-Linux-npm-${{ hashFiles('package-lock.json') }}"

          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=deps-node-modules-${{ hashFiles('package-lock.json') }}"

  # vercel-deploy-dev:
  #   if: github.base_ref == 'dev' && github.event.pull_request.merged == true && needs.setup-pr-closed-dev.outputs.DB_CHANGES == 'true'
  #   needs: setup-pr-closed-dev
  #   runs-on: ubuntu-latest
  #   environment: Preview
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Make shell scripts executable
  #       run: chmod -R +x ./.pscale/cli-helper-scripts/ ./my-scripts/
  # prisma db push can be placed in pscale-cleanup
  # vercel automatically deploys on commits to dev and main so this job is not needed

  # setup-pr-closed-main:
  #   if: github.base_ref == 'main'
  #   runs-on: ubuntu-latest
  #   environment: production

  # pscale-cleanup-pr-main:
  #   if: github.base_ref == 'main'
  #   needs: setup-pr-closed-main
  #   runs-on: ubuntu-latest
  #   environment: production

  # vercel-deploy-main:
  #   if: github.base_ref == 'main' && github.event.pull_request.merged == true
  #   needs: setup-pr-closed-main
  #   runs-on: ubuntu-latest
  #   environment: production
