name: Approve Pscale DR for Github Branch PR (main/dev)

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18.13.0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      GITHUB_BRANCH_NAME: ${{ steps.gh_branch_pr_target.outputs.GITHUB_BRANCH_NAME }}
      GITHUB_PR_TARGET_BRANCH: ${{ steps.gh_branch_pr_target.outputs.GITHUB_PR_TARGET_BRANCH }}
    steps:
      - name: Get Github Branch w/c triggered this workflow and determine target/base branch for the corresponding Pull Request
        id: gh_branch_pr_target
        run: |
          GITHUB_BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          output=$(eval "echo \"$GITHUB_BRANCH_NAME\" | grep -w \"staging\" || true ")
          if [ "$output" == "staging" ]; then
            GITHUB_PR_TARGET_BRANCH="main"
          else
            GITHUB_PR_TARGET_BRANCH="dev"
          fi

          echo "GITHUB_BRANCH_NAME: $GITHUB_BRANCH_NAME"
          echo "GITHUB_PR_TARGET_BRANCH: $GITHUB_PR_TARGET_BRANCH"
          echo "GITHUB_BRANCH_NAME=${GITHUB_BRANCH_NAME}" >> "$GITHUB_OUTPUT"
          echo "GITHUB_PR_TARGET_BRANCH=$GITHUB_PR_TARGET_BRANCH" >> "$GITHUB_OUTPUT"
  dev:
    if: needs.setup.outputs.GITHUB_PR_TARGET_BRANCH == 'dev'
    needs: setup
    uses: ./.github/workflows/pscale-dr-approve.yml
    with:
      gh-environment: Preview
      gh-branch: ${{ needs.setup.outputs.GITHUB_BRANCH_NAME }}
      gh-pr-target: ${{ needs.setup.outputs.GITHUB_PR_TARGET_BRANCH }}
    secrets:
      pscale-token-id: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      pscale-token: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

  main:
    if: needs.setup.outputs.GITHUB_PR_TARGET_BRANCH == 'main'
    needs: setup
    uses: ./.github/workflows/pscale-dr-approve.yml
    with:
      gh-environment: Production
      gh-branch: ${{ needs.setup.outputs.GITHUB_BRANCH_NAME }}
      gh-pr-target: ${{ needs.setup.outputs.GITHUB_PR_TARGET_BRANCH }}
    secrets:
      pscale-token-id: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
      pscale-token: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
